blank_issues_enabled: false
contact_links:
  - name: Have you checked the issues that have been opened?
    about: Check open or close issues to avoid duplicate reports.
    url: https://github.com/zavedyaid/baileys/issues