name: Publish to npm

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack & Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --no-immutable

      # ⬇️ STEP BUILD DIHAPUS KARENA GA ADA SCRIPT NYA

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
